version: '3'
services:
  pokthello-web:
    build:
      context: ./pokthello-web
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./pokthello-web:/app
    ports:
      - '8080:80'
    restart: on-failure
    container_name: pokthello-web
    depends_on:
      - pokthello-api
  pokthello-api:
    build:
      context: ./pokthello-api
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    restart: on-failure
    container_name: pokthello-api
    volumes:
      - /app/node_modules
      - ./pokthello-api:/app
